export enum Protocol {
  Aave = 'Aave',
  Badger = 'Badger',
  Convex = 'Convex',
  Curve = 'Curve',
  mStable = 'mStable',
  Pancakeswap = 'Pancakeswap',
  Quickswap = 'Quickswap',
  Solidly = 'Solidly',
  Sushiswap = 'Sushiswap',
  SpookySwap = 'SpookySwap',
  Swapr = 'Swapr',
  Uniswap = 'Uniswap',
  Yearn = 'Yearn',
}
