export enum RegistryKey {
  Badger = 'BADGER',
  BadgerTree = 'badgerTree',
  Controller = 'controller',
  DevGovernance = 'devGovernance',
  EmissionControl = 'emissionControl',
  Governance = 'governance',
  GovernanceTimelock = 'governanceTimelock',
  Guardian = 'guardian',
  Keeper = 'keeper',
  KeeperAccessControl = 'keeperAccessControl',
  ProxyAdminDev = 'proxyAdminDev',
  ProxyAdminTimelock = 'proxyAdminTimelock',
  RewardsLogger = 'rewardsLogger',
  Timelock = 'timelock',
  ibBTC = 'ibBTC',
}
