name: Service Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Codegen GraphQL
        run: yarn codegen:graphql
      - name: Codegen Contracts
        run: yarn codegen:contracts
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Run Tests
        run: yarn test
