name: Service Tests

on: [pull_request]

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Setup NodeJS
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Codegen
        run: yarn codegen:contracts
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Install mocks.pkg dependencies
        working-directory: ./mocks.pkg
        run: yarn install --frozen-lockfile
      - name: Codegen
        run: yarn codegen:contracts
      - name: Lint Mocks Pkg
        working-directory: ./mocks.pkg
        run: yarn lint
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
          package-manager: yarn
          test-script: yarn test -ci --json --coverage --testLocationInResults --outputFile=report.json
